// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/strategies.proto
// Protobuf Java Version: 4.31.0

package com.verlumen.tradestream.strategies;

/**
 * Protobuf type {@code strategies.RenkoChartParameters}
 */
@com.google.protobuf.Generated
public final class RenkoChartParameters extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:strategies.RenkoChartParameters)
    RenkoChartParametersOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      RenkoChartParameters.class.getName());
  }
  // Use RenkoChartParameters.newBuilder() to construct.
  private RenkoChartParameters(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RenkoChartParameters() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.verlumen.tradestream.strategies.Strategies.internal_static_strategies_RenkoChartParameters_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.verlumen.tradestream.strategies.Strategies.internal_static_strategies_RenkoChartParameters_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.verlumen.tradestream.strategies.RenkoChartParameters.class, com.verlumen.tradestream.strategies.RenkoChartParameters.Builder.class);
  }

  private int bitField0_;
  public static final int BRICKSIZE_FIELD_NUMBER = 1;
  private double brickSize_ = 0D;
  /**
   * <code>double brickSize = 1;</code>
   * @return Whether the brickSize field is set.
   */
  @java.lang.Override
  public boolean hasBrickSize() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>double brickSize = 1;</code>
   * @return The brickSize.
   */
  @java.lang.Override
  public double getBrickSize() {
    return brickSize_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeDouble(1, brickSize_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, brickSize_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.verlumen.tradestream.strategies.RenkoChartParameters)) {
      return super.equals(obj);
    }
    com.verlumen.tradestream.strategies.RenkoChartParameters other = (com.verlumen.tradestream.strategies.RenkoChartParameters) obj;

    if (hasBrickSize() != other.hasBrickSize()) return false;
    if (hasBrickSize()) {
      if (java.lang.Double.doubleToLongBits(getBrickSize())
          != java.lang.Double.doubleToLongBits(
              other.getBrickSize())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBrickSize()) {
      hash = (37 * hash) + BRICKSIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBrickSize()));
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.verlumen.tradestream.strategies.RenkoChartParameters parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.verlumen.tradestream.strategies.RenkoChartParameters prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code strategies.RenkoChartParameters}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:strategies.RenkoChartParameters)
      com.verlumen.tradestream.strategies.RenkoChartParametersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.verlumen.tradestream.strategies.Strategies.internal_static_strategies_RenkoChartParameters_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.verlumen.tradestream.strategies.Strategies.internal_static_strategies_RenkoChartParameters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.verlumen.tradestream.strategies.RenkoChartParameters.class, com.verlumen.tradestream.strategies.RenkoChartParameters.Builder.class);
    }

    // Construct using com.verlumen.tradestream.strategies.RenkoChartParameters.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      brickSize_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.verlumen.tradestream.strategies.Strategies.internal_static_strategies_RenkoChartParameters_descriptor;
    }

    @java.lang.Override
    public com.verlumen.tradestream.strategies.RenkoChartParameters getDefaultInstanceForType() {
      return com.verlumen.tradestream.strategies.RenkoChartParameters.getDefaultInstance();
    }

    @java.lang.Override
    public com.verlumen.tradestream.strategies.RenkoChartParameters build() {
      com.verlumen.tradestream.strategies.RenkoChartParameters result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.verlumen.tradestream.strategies.RenkoChartParameters buildPartial() {
      com.verlumen.tradestream.strategies.RenkoChartParameters result = new com.verlumen.tradestream.strategies.RenkoChartParameters(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.verlumen.tradestream.strategies.RenkoChartParameters result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.brickSize_ = brickSize_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.verlumen.tradestream.strategies.RenkoChartParameters) {
        return mergeFrom((com.verlumen.tradestream.strategies.RenkoChartParameters)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.verlumen.tradestream.strategies.RenkoChartParameters other) {
      if (other == com.verlumen.tradestream.strategies.RenkoChartParameters.getDefaultInstance()) return this;
      if (other.hasBrickSize()) {
        setBrickSize(other.getBrickSize());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              brickSize_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double brickSize_ ;
    /**
     * <code>double brickSize = 1;</code>
     * @return Whether the brickSize field is set.
     */
    @java.lang.Override
    public boolean hasBrickSize() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>double brickSize = 1;</code>
     * @return The brickSize.
     */
    @java.lang.Override
    public double getBrickSize() {
      return brickSize_;
    }
    /**
     * <code>double brickSize = 1;</code>
     * @param value The brickSize to set.
     * @return This builder for chaining.
     */
    public Builder setBrickSize(double value) {

      brickSize_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double brickSize = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrickSize() {
      bitField0_ = (bitField0_ & ~0x00000001);
      brickSize_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:strategies.RenkoChartParameters)
  }

  // @@protoc_insertion_point(class_scope:strategies.RenkoChartParameters)
  private static final com.verlumen.tradestream.strategies.RenkoChartParameters DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.verlumen.tradestream.strategies.RenkoChartParameters();
  }

  public static com.verlumen.tradestream.strategies.RenkoChartParameters getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RenkoChartParameters>
      PARSER = new com.google.protobuf.AbstractParser<RenkoChartParameters>() {
    @java.lang.Override
    public RenkoChartParameters parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RenkoChartParameters> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RenkoChartParameters> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.verlumen.tradestream.strategies.RenkoChartParameters getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

