load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "ParamRangeTest",
    srcs = ["ParamRangeTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestream/backtesting/params:param_range",
    ],
)
