java_test(
    name = "param_config_test",
    srcs = ["RainbowOscillatorParamConfigTest.java"],
    test_class = "com.verlumen.tradestream.strategies.rainbowoscillator.RainbowOscillatorParamConfigTest",
    deps = [
        "//protos:strategies_java_proto",
        "//protos:strategies_proto",
        "//src/main/java/com/verlumen/tradestream/strategies/rainbowoscillator:param_config",
        "//third_party/java:guava",
        "//third_party/java:jenetics",
        "//third_party/java:junit",
        "//third_party/java:protobuf_java",
        "//third_party/java:truth",
    ],
)

java_test(
    name = "strategy_factory_test",
    srcs = ["RainbowOscillatorStrategyFactoryTest.java"],
    test_class = "com.verlumen.tradestream.strategies.rainbowoscillator.RainbowOscillatorStrategyFactoryTest",
    deps = [
        "//protos:strategies_java_proto",
        "//protos:strategies_proto",
        "//src/main/java/com/verlumen/tradestream/strategies/rainbowoscillator:strategy_factory",
        "//third_party/java:junit",
        "//third_party/java:protobuf_java",
        "//third_party/java:ta4j_core",
        "//third_party/java:truth",
    ],
)
