load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")

kt_jvm_library(
    name = "moving_average_params",
    srcs = ["MovingAverageParams.kt"],
    deps = [
        "//src/main/java/com/verlumen/tradestream/backtesting:param_config",
    ],
)
