java_library(
  name = "bar_series_builder",
  srcs = ["BarSeriesBuilder.java"],
  deps = [
    "//third_party:guava",
    "//third_party:protobuf_java",
    "//third_party:protobuf_java_util",
    "//third_party:ta4j_core",
  ],
)
