apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tradestream.fullname" . }}-data-ingestion
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tradestream.name" . }}
    component: data-ingestion
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.dataIngestion.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tradestream.name" . }}
      component: data-ingestion
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "tradestream.name" . }}
        component: data-ingestion
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: wait-for-secret
          image: bitnami/kubectl:1.21
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get secret coinmarketcap-api-key -n {{ .Release.Namespace }}; do echo "Waiting for secret..."; sleep 2; done
      containers:
        - name: data-ingestion
          image: "{{ .Values.dataIngestion.image.repository }}:{{ .Values.dataIngestion.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.dataIngestion.service.port }}
          env:
            - name: COINMARKETCAP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: coinmarketcap-api-key
                  key: apiKey
