apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ include "tradestream.fullname" . }}-flink-beam
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tradestream.name" . }}
    component: flink-beam
    release: {{ .Release.Name }}
spec:
  image: {{ .Values.flink.image.repository }}:{{ .Values.flink.image.tag }}
  imagePullPolicy: {{ default "IfNotPresent" .Values.flink.image.pullPolicy }}
  flinkVersion: {{ .Values.flink.version }}
  flinkConfiguration:
    {{- toYaml .Values.flink.configuration | nindent 4 }}
  serviceAccount: {{ .Values.flink.serviceAccount }}
  jobManager:
    resource:
      memory: {{ .Values.flink.jobManager.memory }}
      cpu: {{ .Values.flink.jobManager.cpu }}
  taskManager:
    resource:
      memory: {{ .Values.flink.taskManager.memory }}
      cpu: {{ .Values.flink.taskManager.cpu }}
  job:
    entryClass: {{ .Values.flink.job.entryClass }}
    jarURI: {{ .Values.flink.job.jarURI }}
    args: 
      {{- toYaml .Values.flink.job.args | nindent 6 }}
    parallelism: {{ .Values.flink.job.parallelism }}
    upgradeMode: {{ .Values.flink.job.upgradeMode }}
