apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tradestream.fullname" . }}-ha
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tradestream.name" . }}
    component: data-pipeline
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: cbs-rbd
