apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tradestream.fullname" . }}-kafka-topic-init
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tradestream.name" . }}
    component: kafka-topic-creator
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-topic-creator
          image: bitnami/kafka:latest
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for Kafka broker to be ready..."
              until /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server {{ .Release.Name }}-kafka-controller:9092 --list; do
                echo "Kafka is not ready. Retrying..."
                sleep 5
              done

              echo "Creating Kafka topics..."
              /opt/bitnami/kafka/bin/kafka-topics.sh \
                --bootstrap-server {{ .Release.Name }}-kafka-controller:9092 \
                --create \
                --if-not-exists \
                --topic {{ .Values.kafka.topics.candles.name }} \
                --partitions {{ .Values.kafka.topics.candles.partitions }} \
                --replication-factor {{ .Values.kafka.topics.candles.replicationFactor }} \
                --config retention.ms={{ .Values.kafka.topics.candles.retentionMs }} \
                --config cleanup.policy={{ .Values.kafka.topics.candles.cleanupPolicy }}
