apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: candles
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: my-tradestream-kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
