apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tradestream.fullname" . }}-create-topic
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tradestream.name" . }}
    component: kafka-topic-creator
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-kafka
          image: bitnami/kafka:latest
          command:
            - /bin/bash
            - -c
            - |
              until /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server my-tradestream-kafka-controller:9092 --list; do
                echo "Waiting for Kafka to be ready..."
                sleep 5
              done
      containers:
      - name: create-topics
        image: bitnami/kafka:latest
        command:
        - /bin/bash
        - -c
        - |
          /opt/bitnami/kafka/bin/kafka-topics.sh \
            --bootstrap-server my-tradestream-kafka:9092 \
            --create \
            --if-not-exists \
            --topic candles \
            --partitions 3 \
            --replication-factor 2 \
            --config retention.ms=604800000 \
            --config cleanup.policy=delete
