apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ include "tradestream.fullname" . }}-flink-beam
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tradestream.name" . }}
    component: flink-beam
    release: {{ .Release.Name }}
spec:
  image: {{ .Values.pipeline.image.repository }}:{{ .Values.pipeline.image.tag }}
  imagePullPolicy: {{ default "IfNotPresent" .Values.pipeline.image.pullPolicy }}
  flinkVersion: {{ .Values.pipeline.version }}
  flinkConfiguration:
    {{- toYaml .Values.pipeline.configuration | nindent 4 }}
  serviceAccount: {{ .Values.pipeline.serviceAccount }}
  jobManager:
    resource:
      memory: {{ .Values.pipeline.jobManager.memory }}
      cpu: {{ .Values.pipeline.jobManager.cpu }}
  taskManager:
    resource:
      memory: {{ .Values.pipeline.taskManager.memory }}
      cpu: {{ .Values.pipeline.taskManager.cpu }}
  job:
    entryClass: {{ .Values.pipeline.job.entryClass }}
    jarURI: {{ .Values.pipeline.job.jarURI }}
    args: 
      {{- toYaml .Values.pipeline.job.args | nindent 6 }}
    parallelism: {{ .Values.pipeline.job.parallelism }}
    upgradeMode: {{ .Values.pipeline.job.upgradeMode }}
