apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tradestream.fullname" . }}-strategy-engine
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tradestream.name" . }}
    component: strategy-engine
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.strategyEngine.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "tradestream.name" . }}
      component: strategy-engine
  template:
    metadata:
      labels:
        app: {{ include "tradestream.name" . }}
        component: strategy-engine
    spec:
      containers:
        - name: strategy-engine
          args:
          {{- range .Values.strategyEngine.args }}
            - {{ . }}
          {{- end }}
          image: "{{ .Values.strategyEngine.image.repository }}:{{ .Values.strategyEngine.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.strategyEngine.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.strategyEngine.service.port }}
