{{- if .Values.strategyMonitorUi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tradestream.fullname" . }}-strategy-monitor-ui
  labels:
    {{- include "tradestream.labels" . | nindent 4 }}
    app.kubernetes.io/component: strategy-monitor-ui
spec:
  replicas: {{ .Values.strategyMonitorUi.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "tradestream.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: strategy-monitor-ui
  template:
    metadata:
      labels:
        {{- include "tradestream.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: strategy-monitor-ui
    spec:
      containers:
        - name: strategy-monitor-ui
          image: "{{ .Values.strategyMonitorUi.image.repository }}:{{ .Values.strategyMonitorUi.image.tag }}"
          imagePullPolicy: {{ .Values.strategyMonitorUi.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.strategyMonitorUi.service.port | default 8080 }}
              protocol: TCP
          env:
            - name: API_BASE_URL
              value: "http://{{ include "tradestream.fullname" . }}-strategy-monitor-api:{{ .Values.strategyMonitorApi.service.port | default 8080 }}"
          resources:
            {{- toYaml .Values.strategyMonitorUi.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tradestream.fullname" . }}-strategy-monitor-ui
  labels:
    {{- include "tradestream.labels" . | nindent 4 }}
    app.kubernetes.io/component: strategy-monitor-ui
spec:
  type: {{ .Values.strategyMonitorUi.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.strategyMonitorUi.service.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tradestream.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: strategy-monitor-ui
{{- end }} 