java_test(
    name = "param_config_test",
    srcs = ["RenkoChartParamConfigTest.java"],
    test_class = "com.verlumen.tradestream.strategies.renkochart.RenkoChartParamConfigTest",
    visibility = ["//src/test/java/com/verlumen/tradestream/strategies:__subpackages__"],
    deps = [
        "//protos:strategies_java_proto",
        "//src/main/java/com/verlumen/tradestream/strategies/renkochart:param_config",
        "//third_party/java:guava",
        "//third_party/java:jenetics",
        "//third_party/java:junit",
        "//third_party/java:protobuf_java",
        "//third_party/java:truth",
    ],
)

java_test(
    name = "strategy_factory_test",
    srcs = ["RenkoChartStrategyFactoryTest.java"],
    test_class = "com.verlumen.tradestream.strategies.renkochart.RenkoChartStrategyFactoryTest",
    visibility = ["//src/test/java/com/verlumen/tradestream/strategies:__subpackages__"],
    deps = [
        "//protos:strategies_java_proto",
        "//src/main/java/com/verlumen/tradestream/strategies/renkochart:strategy_factory",
        "//third_party/java:guava",
        "//third_party/java:jenetics",
        "//third_party/java:junit",
        "//third_party/java:protobuf_java",
        "//third_party/java:ta4j_core",
        "//third_party/java:truth",
    ],
)
