java_test(
    name = "param_config_test",
    srcs = ["VolumeProfileDeviationsParamConfigTest.java"],
    test_class = "com.verlumen.tradestream.strategies.volumeprofiledeviations.VolumeProfileDeviationsParamConfigTest",
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/verlumen/tradestream/strategies/volumeprofiledeviations:param_config",
        "//third_party/java:junit",
        "//third_party/java:truth",
        "//third_party/java:guava",
        "//third_party/java:jenetics",
        "//third_party/java:protobuf_java",
        "//protos:strategies_java_proto",
    ],
)

java_test(
    name = "strategy_factory_test",
    srcs = ["VolumeProfileDeviationsStrategyFactoryTest.java"],
    test_class = "com.verlumen.tradestream.strategies.volumeprofiledeviations.VolumeProfileDeviationsStrategyFactoryTest",
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/verlumen/tradestream/strategies/volumeprofiledeviations:strategy_factory",
        "//third_party/java:junit",
        "//third_party/java:truth",
        "//third_party/java:ta4j_core",
        "//protos:strategies_java_proto",
    ],
) 