load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "endpoint",
    srcs = ["Endpoint.java"],
    deps = [
        "//third_party:grpc_java_api",
    ],
)