load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "GetLastNElementsDoFnTest",
    srcs = ["GetLastNElementsDoFnTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestream/transforms:get_last_n_elements_do_fn",
        "//third_party:auto_value",
        "//third_party:guava",
        "//third_party:junit",
    ],
)
