"""Pine Script template generator for TradingView alerts.

Generates Pine Script v5 indicator code that sends webhook alerts
compatible with the TradeStream TradingView integration endpoint.
"""

from services.tradingview_integration.models import PineScriptConfig


def generate_webhook_indicator(config: PineScriptConfig) -> str:
    """Generate a Pine Script v5 indicator that fires webhook alerts.

    The generated script creates a simple moving average crossover indicator
    as a template. Users can modify the signal logic while keeping the
    alert payload format compatible with TradeStream.
    """
    ticker_expr = f'"{config.ticker}"' if config.ticker else "syminfo.ticker"

    # Build the alert payload JSON template
    buy_payload_parts = [
        f'"ticker": " + {ticker_expr} + "',
        '"action": "buy"',
        '"strategy": "' + _escape_pine(config.strategy_name) + '"',
        '"price": " + str.tostring(close) + "',
    ]
    sell_payload_parts = [
        f'"ticker": " + {ticker_expr} + "',
        '"action": "sell"',
        '"strategy": "' + _escape_pine(config.strategy_name) + '"',
        '"price": " + str.tostring(close) + "',
    ]

    if config.include_stop_loss:
        buy_payload_parts.append('"stoploss": " + str.tostring(close * 0.98) + "')
        sell_payload_parts.append('"stoploss": " + str.tostring(close * 1.02) + "')

    if config.include_take_profit:
        buy_payload_parts.append('"takeprofit": " + str.tostring(close * 1.04) + "')
        sell_payload_parts.append('"takeprofit": " + str.tostring(close * 0.96) + "')

    if config.include_quantity:
        buy_payload_parts.append('"quantity": 1.0')
        sell_payload_parts.append('"quantity": 1.0')

    buy_payload_parts.append('"interval": " + timeframe.period + "')
    buy_payload_parts.append('"exchange": " + syminfo.prefix + "')
    sell_payload_parts.append('"interval": " + timeframe.period + "')
    sell_payload_parts.append('"exchange": " + syminfo.prefix + "')

    buy_json = _build_json_string(buy_payload_parts)
    sell_json = _build_json_string(sell_payload_parts)

    script = f"""//@version=5
// Auto-generated by TradeStream — TradingView Webhook Integration
// Strategy: {_escape_pine(config.strategy_name)}
// Webhook URL: {config.webhook_url}
//
// SETUP INSTRUCTIONS:
// 1. Add this indicator to your TradingView chart
// 2. Create an alert on this indicator
// 3. Set "Webhook URL" to: {config.webhook_url}
// 4. Set "Message" to: {{{{plot("buy_alert")}}}} or {{{{plot("sell_alert")}}}}
//    OR use the built-in alert() calls which fire automatically
//
// Modify the signal logic below to match your trading strategy.
// Keep the alert JSON format unchanged for TradeStream compatibility.

indicator("{_escape_pine(config.strategy_name)} — TradeStream", overlay=true)

// === SIGNAL LOGIC (customize this section) ===
fastLen = input.int(10, "Fast MA Length", minval=1)
slowLen = input.int(20, "Slow MA Length", minval=1)

fastMA = ta.sma(close, fastLen)
slowMA = ta.sma(close, slowLen)

buySignal = ta.crossover(fastMA, slowMA)
sellSignal = ta.crossunder(fastMA, slowMA)

plot(fastMA, "Fast MA", color=color.blue)
plot(slowMA, "Slow MA", color=color.red)

// === ALERT PAYLOADS (keep this format for TradeStream) ===
buyPayload = '{buy_json}
sellPayload = '{sell_json}

if buySignal
    alert(buyPayload, alert.freq_once_per_bar_close)

if sellSignal
    alert(sellPayload, alert.freq_once_per_bar_close)

// Visual markers
plotshape(buySignal, "Buy", shape.triangleup, location.belowbar, color.green, size=size.small)
plotshape(sellSignal, "Sell", shape.triangledown, location.abovebar, color.red, size=size.small)
"""
    return script


def generate_strategy_template(config: PineScriptConfig) -> str:
    """Generate a Pine Script v5 strategy template with webhook alerts.

    Unlike the indicator version, this uses strategy.*() calls for
    backtesting in TradingView, with alert_message for webhook delivery.
    """
    ticker_expr = f'"{config.ticker}"' if config.ticker else "syminfo.ticker"

    script = f"""//@version=5
// Auto-generated by TradeStream — TradingView Strategy Template
// Strategy: {_escape_pine(config.strategy_name)}
// Webhook URL: {config.webhook_url}
//
// This is a Pine Script STRATEGY for backtesting + live alerts.
// Set the webhook URL in your alert configuration.

strategy("{_escape_pine(config.strategy_name)} — TradeStream", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// === STRATEGY PARAMETERS ===
fastLen = input.int(10, "Fast MA Length", minval=1)
slowLen = input.int(20, "Slow MA Length", minval=1)

// === INDICATORS ===
fastMA = ta.sma(close, fastLen)
slowMA = ta.sma(close, slowLen)

plot(fastMA, "Fast MA", color=color.blue)
plot(slowMA, "Slow MA", color=color.red)

// === ENTRY/EXIT LOGIC ===
buySignal = ta.crossover(fastMA, slowMA)
sellSignal = ta.crossunder(fastMA, slowMA)

// === WEBHOOK PAYLOAD TEMPLATES ===
buyMsg = '{{"ticker": "' + {ticker_expr} + '", "action": "buy", "strategy": "{_escape_pine(config.strategy_name)}", "price": ' + str.tostring(close) + '}}'
sellMsg = '{{"ticker": "' + {ticker_expr} + '", "action": "sell", "strategy": "{_escape_pine(config.strategy_name)}", "price": ' + str.tostring(close) + '}}'

if buySignal
    strategy.entry("Long", strategy.long, alert_message=buyMsg)

if sellSignal
    strategy.close("Long", alert_message=sellMsg)
"""
    return script


def _escape_pine(text: str) -> str:
    """Escape special characters for Pine Script string literals."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")


def _build_json_string(parts: list[str]) -> str:
    """Build a Pine Script concatenated JSON string from parts."""
    inner = ", ".join(parts)
    return '{" + ' + inner + ' + "}'
