java_library(
    name = "movingaverages",
    srcs = glob(["*.java"]),
    deps = [
        "//:strategy_factory",
        "@maven//:org_ta4j_ta4j_core",
        "//protos:strategies_java_proto",
    ],
)
