load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "CurrencyPairTest",
    srcs = ["CurrencyPairTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestream/instruments:currency",
        "//src/main/java/com/verlumen/tradestream/instruments:currency_pair",
        "//third_party:junit",
        "//third_party:truth",
    ],
)
