load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "CurrencyPairTest",
    srcs = ["CurrencyPairTest.java"],
    deps = [
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "//src/main/java/com/verlumen/tradestream/instruments:currency_pair",
    ],
)
