java_test(
    name = "param_config_test",
    srcs = ["DemaTemaCrossoverParamConfigTest.java"],
    test_class = "com.verlumen.tradestream.strategies.dematemacrossover.DemaTemaCrossoverParamConfigTest",
    deps = [
        "//protos:strategies_java_proto",
        "//protos:strategies_proto",
        "//src/main/java/com/verlumen/tradestream/strategies/dematemacrossover:param_config",
        "//third_party/java:guava",
        "//third_party/java:jenetics",
        "//third_party/java:junit",
        "//third_party/java:protobuf_java",
        "//third_party/java:truth",
    ],
)

java_test(
    name = "strategy_factory_test",
    srcs = ["DemaTemaCrossoverStrategyFactoryTest.java"],
    test_class = "com.verlumen.tradestream.strategies.dematemacrossover.DemaTemaCrossoverStrategyFactoryTest",
    deps = [
        "//protos:strategies_java_proto",
        "//protos:strategies_proto",
        "//src/main/java/com/verlumen/tradestream/strategies/dematemacrossover:strategy_factory",
        "//third_party/java:junit",
        "//third_party/java:protobuf_java",
        "//third_party/java:ta4j_core",
        "//third_party/java:truth",
    ],
)
