java_test(
    name = "param_config_test",
    srcs = ["ObvEmaParamConfigTest.java"],
    test_class = "com.verlumen.tradestream.strategies.obvema.ObvEmaParamConfigTest",
    deps = [
        "//protos:strategies_java_proto",
        "//src/main/java/com/verlumen/tradestream/strategies/obvema:param_config",
        "//third_party/java:guava",
        "//third_party/java:jenetics",
        "//third_party/java:junit",
        "//third_party/java:protobuf_java",
        "//third_party/java:truth",
    ],
)

java_test(
    name = "strategy_factory_test",
    srcs = ["ObvEmaStrategyFactoryTest.java"],
    test_class = "com.verlumen.tradestream.strategies.obvema.ObvEmaStrategyFactoryTest",
    deps = [
        "//protos:strategies_java_proto",
        "//src/main/java/com/verlumen/tradestream/strategies/obvema:strategy_factory",
        "//third_party/java:junit",
        "//third_party/java:protobuf_java",
        "//third_party/java:ta4j_core",
        "//third_party/java:truth",
    ],
)
