"""
MCP server for strategy specs and implementations management.
Exposes tools for the Learning Agent to query and submit strategy specs.
"""

import json
from typing import Any, Dict, List

from mcp.server import Server
from mcp.types import TextContent, Tool

from services.strategy_db_mcp.postgres_client import PostgresClient


def create_server(postgres_client: PostgresClient) -> Server:
    """Create and configure the strategy database MCP server with all tools."""
    server = Server("strategy-db-mcp")

    @server.list_tools()
    async def list_tools() -> List[Tool]:
        return [
            Tool(
                name="get_top_specs",
                description="Get top performing strategy specs ranked by average Sharpe ratio.",
                inputSchema={
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer",
                            "default": 10,
                            "maximum": 100,
                            "description": "Maximum specs to return.",
                        },
                        "offset": {
                            "type": "integer",
                            "default": 0,
                            "description": "Number of specs to skip for pagination.",
                        },
                        "source": {
                            "type": "string",
                            "enum": ["CANONICAL", "LLM_GENERATED", "ALL"],
                            "default": "ALL",
                            "description": "Filter by spec source.",
                        },
                    },
                },
            ),
            Tool(
                name="get_implementations",
                description="Get implementations for a strategy spec with performance metrics.",
                inputSchema={
                    "type": "object",
                    "properties": {
                        "spec_id": {
                            "type": "string",
                            "description": "Strategy spec UUID.",
                        },
                        "status": {
                            "type": "string",
                            "enum": [
                                "CANDIDATE",
                                "VALIDATED",
                                "DEPLOYED",
                                "RETIRED",
                                "ALL",
                            ],
                            "default": "VALIDATED",
                            "description": "Filter by implementation status.",
                        },
                        "limit": {
                            "type": "integer",
                            "default": 10,
                            "maximum": 100,
                            "description": "Maximum implementations to return.",
                        },
                        "offset": {
                            "type": "integer",
                            "default": 0,
                            "description": "Number of implementations to skip.",
                        },
                    },
                    "required": ["spec_id"],
                },
            ),
            Tool(
                name="submit_new_spec",
                description="Submit a new strategy spec generated by the Learning Agent.",
                inputSchema={
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "description": "Unique strategy spec name.",
                        },
                        "indicators": {
                            "type": "array",
                            "description": "List of technical indicator configurations.",
                        },
                        "entry_conditions": {
                            "type": "array",
                            "description": "List of entry condition rules.",
                        },
                        "exit_conditions": {
                            "type": "array",
                            "description": "List of exit condition rules.",
                        },
                        "parameters": {
                            "type": "array",
                            "description": "List of tunable parameter definitions.",
                        },
                        "description": {
                            "type": "string",
                            "description": "Human-readable description of the strategy.",
                        },
                        "reasoning": {
                            "type": "string",
                            "description": "LLM reasoning behind the strategy design.",
                        },
                    },
                    "required": [
                        "name",
                        "indicators",
                        "entry_conditions",
                        "exit_conditions",
                        "parameters",
                    ],
                },
            ),
        ]

    @server.call_tool()
    async def call_tool(name: str, arguments: Dict[str, Any]) -> List[TextContent]:
        if name == "get_top_specs":
            result = await postgres_client.get_top_specs(
                limit=arguments.get("limit", 10),
                offset=arguments.get("offset", 0),
                source=arguments.get("source", "ALL"),
            )
            return [TextContent(type="text", text=json.dumps(result, default=str))]

        elif name == "get_implementations":
            result = await postgres_client.get_implementations(
                spec_id=arguments["spec_id"],
                status=arguments.get("status", "VALIDATED"),
                limit=arguments.get("limit", 10),
                offset=arguments.get("offset", 0),
            )
            return [TextContent(type="text", text=json.dumps(result, default=str))]

        elif name == "submit_new_spec":
            result = await postgres_client.submit_new_spec(
                name=arguments["name"],
                indicators=arguments["indicators"],
                entry_conditions=arguments["entry_conditions"],
                exit_conditions=arguments["exit_conditions"],
                parameters=arguments["parameters"],
                description=arguments.get("description"),
                reasoning=arguments.get("reasoning"),
            )
            return [TextContent(type="text", text=json.dumps(result, default=str))]

        else:
            return [
                TextContent(
                    type="text",
                    text=json.dumps({"error": f"Unknown tool: {name}"}),
                )
            ]

    return server
