load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "AdxStochasticStrategyFactoryTest",
    srcs = ["AdxStochasticStrategyFactoryTest.java"],
    deps = [
        "//protos:strategies_java_proto",
        "//src/main/java/com/verlumen/tradestream/strategies:strategy_factory",
        "//src/main/java/com/verlumen/tradestream/strategies/oscillators:oscillators_lib",
        "//third_party:flogger",
        "//third_party:guava",
        "//third_party:junit",
        "//third_party:protobuf_java",
        "//third_party:mockito_core",
        "//third_party:truth",
        "//third_party:ta4j_core",
    ],
)

java_test(
    name = "SmaRsiStrategyFactoryTest",
    srcs = ["SmaRsiStrategyFactoryTest.java"],
    deps = [
        "//protos:strategies_java_proto",
        "//src/main/java/com/verlumen/tradestream/strategies:strategy_factory",
        "//src/main/java/com/verlumen/tradestream/strategies/oscillators:oscillators_lib",
        "//third_party:flogger",
        "//third_party:guava",
        "//third_party:junit",
        "//third_party:protobuf_java",
        "//third_party:mockito_core",
        "//third_party:truth",
        "//third_party:ta4j_core",
    ],
)
