package(default_visibility = ["//visibility:public"])

load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "param_range",
    srcs = ["ParamRange.java"],
    deps = [
        "//third_party:auto_value",
        "//third_party:guava",
    ],
)
