java_library(
    name = "param_config",
    srcs = ["ParamConfig.java"],
    deps = [
        "//third_party:guava",
        "//third_party:jenetics",
        "//third_party:protobuf_java",
    ],
)
