load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "get_last_n_elements_do_fn",
    srcs = ["GetLastNElementsDoFn.java"],
    deps = [
        "//third_party:auto_value",
        "//third_party:beam_sdks_java_core",
        "//third_party:commons_collections4",
        "//third_party:guava",
    ],
)
