load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
  name = "timestamps",
  srcs = ["Timestamps.java"],
  deps = [
    "//third_party:protobuf_java",
  ],
)
