java_test(
    name = "BarSeriesBuilderTest",
    srcs = ["BarSeriesBuilderTest.java"],
    deps = [
        ":bar_series_builder",
        "//third_party:junit",
        "//third_party:guava",
        "//third_party:protobuf_java",
        "//third_party:protobuf_java_util",
        "//third_party:ta4j_core",
        "//protos:marketdata_java_proto",
    ],
)
