package com.verlumen.tradestream.strategies.configurable.llm;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.verlumen.tradestream.strategies.configurable.StrategyConfig;
import com.verlumen.tradestream.strategies.configurable.StrategyConfigLoader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Logger;

/**
 * Stores experiment results: generated specs, backtest results, and summary. Writes JSON files and
 * generates SQL INSERT statements for the strategy_specs table.
 */
public final class ResultsStorage {
  private static final Logger logger = Logger.getLogger(ResultsStorage.class.getName());
  private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

  private final Path outputDir;

  public ResultsStorage(Path outputDir) {
    this.outputDir = outputDir;
  }

  /** Save full experiment results to the output directory. */
  public void saveResults(ExperimentRunner.ExperimentResults results) throws IOException {
    Files.createDirectories(outputDir);

    // Save summary report
    String report = results.generateReport();
    Files.writeString(outputDir.resolve("experiment_report.txt"), report, StandardCharsets.UTF_8);
    logger.info("Saved experiment report");

    // Save each valid strategy as YAML
    Path strategiesDir = outputDir.resolve("generated_strategies");
    Files.createDirectories(strategiesDir);

    for (ExperimentRunner.RankedStrategy rs : results.getRankedStrategies()) {
      if (rs.getBacktestResult().isSuccessful() && rs.getConfig().getName() != null) {
        String filename = rs.getConfig().getName().toLowerCase() + ".yaml";
        // Write as JSON (our loader can parse both)
        String json = StrategyConfigLoader.toJson(rs.getConfig());
        Files.writeString(strategiesDir.resolve(filename + ".json"), json, StandardCharsets.UTF_8);
      }
    }
    logger.info("Saved " + results.getRankedStrategies().size() + " generated strategies");

    // Save SQL inserts for strategy_specs table
    String sql = generateSqlInserts(results);
    Files.writeString(outputDir.resolve("insert_generated_specs.sql"), sql, StandardCharsets.UTF_8);
    logger.info("Saved SQL insert statements");

    // Save full results as JSON
    Map<String, Object> fullResults = buildResultsMap(results);
    Files.writeString(
        outputDir.resolve("experiment_results.json"),
        GSON.toJson(fullResults),
        StandardCharsets.UTF_8);
    logger.info("Saved full results JSON");
  }

  /** Generate SQL INSERT statements for strategy_specs table. */
  public String generateSqlInserts(ExperimentRunner.ExperimentResults results) {
    StringBuilder sql = new StringBuilder();
    sql.append("-- Auto-generated by LLM Spec Generation Experiment\n");
    sql.append("-- Source: LLM_GENERATED\n\n");

    for (ExperimentRunner.RankedStrategy rs : results.getRankedStrategies()) {
      StrategyConfig config = rs.getConfig();
      BacktestPipeline.BacktestResult bt = rs.getBacktestResult();

      if (!bt.isSuccessful() || config.getName() == null) continue;

      String indicatorsJson = GSON.toJson(config.getIndicators());
      String entryJson = GSON.toJson(config.getEntryConditions());
      String exitJson = GSON.toJson(config.getExitConditions());
      String paramsJson = GSON.toJson(config.getParameters());

      String description =
          config.getDescription() != null
              ? config.getDescription().replace("'", "''")
              : "LLM-generated strategy";
      String complexity =
          config.getComplexity() != null ? config.getComplexity().toUpperCase() : "MEDIUM";

      // Backtest metrics
      Map<String, Object> backtestMetrics = new LinkedHashMap<>();
      backtestMetrics.put("gross_return", bt.getGrossReturn());
      backtestMetrics.put("sharpe_approx", bt.getSharpeApprox());
      backtestMetrics.put("win_rate", bt.getWinRate());
      backtestMetrics.put("num_trades", bt.getNumTrades());
      backtestMetrics.put("return_over_max_drawdown", bt.getReturnOverMaxDrawdown());
      backtestMetrics.put("vs_buy_hold_ratio", bt.getVsBuyHoldRatio());

      sql.append(
          String.format(
              "INSERT INTO strategy_specs "
                  + "(id, name, version, description, complexity, indicators, "
                  + "entry_conditions, exit_conditions, parameters, source, "
                  + "source_citation, tags, is_active, created_at, updated_at) "
                  + "VALUES (\n"
                  + "  gen_random_uuid(),\n"
                  + "  '%s',\n"
                  + "  1,\n"
                  + "  '%s',\n"
                  + "  '%s',\n"
                  + "  '%s'::jsonb,\n"
                  + "  '%s'::jsonb,\n"
                  + "  '%s'::jsonb,\n"
                  + "  '%s'::jsonb,\n"
                  + "  'LLM_GENERATED',\n"
                  + "  'Phase 2 validation experiment - OpenRouter API',\n"
                  + "  ARRAY['llm-generated', 'phase-2-validation'],\n"
                  + "  true,\n"
                  + "  NOW(),\n"
                  + "  NOW()\n"
                  + ") ON CONFLICT (name) DO NOTHING;\n\n",
              config.getName().replace("'", "''"),
              description,
              complexity,
              indicatorsJson.replace("'", "''"),
              entryJson.replace("'", "''"),
              exitJson.replace("'", "''"),
              paramsJson.replace("'", "''")));

      // Also insert into strategy_implementations with backtest metrics
      sql.append(
          String.format(
              "INSERT INTO strategy_implementations "
                  + "(id, spec_id, parameters, discovered_by, backtest_metrics, status, "
                  + "notes, created_at, updated_at) "
                  + "SELECT gen_random_uuid(), s.id, '%s'::jsonb, 'LLM', '%s'::jsonb, "
                  + "'CANDIDATE', 'Auto-generated by Phase 2 LLM experiment', NOW(), NOW() "
                  + "FROM strategy_specs s WHERE s.name = '%s' "
                  + "ON CONFLICT DO NOTHING;\n\n",
              paramsJson.replace("'", "''"),
              GSON.toJson(backtestMetrics).replace("'", "''"),
              config.getName().replace("'", "''")));
    }

    return sql.toString();
  }

  private Map<String, Object> buildResultsMap(ExperimentRunner.ExperimentResults results) {
    Map<String, Object> map = new LinkedHashMap<>();
    map.put("experiment", "phase_2_llm_spec_generation");

    Map<String, Object> summary = new LinkedHashMap<>();
    summary.put("total_generated", results.getTotalGenerated());
    summary.put("syntax_valid", results.getSyntaxValidCount());
    summary.put("syntax_valid_rate", results.getSyntaxValidRate());
    summary.put("logic_valid", results.getLogicValidCount());
    summary.put("logic_valid_rate", results.getLogicValidRate());
    summary.put("novel", results.getNovelCount());
    summary.put("novel_rate", results.getNovelRate());
    summary.put("fully_valid", results.getFullyValidCount());
    summary.put("successful_backtests", results.getSuccessfulBacktestCount());
    map.put("summary", summary);

    Map<String, Object> criteria = new LinkedHashMap<>();
    criteria.put("syntax_valid_target", 0.80);
    criteria.put("syntax_valid_passed", results.getSyntaxValidRate() >= 0.80);
    criteria.put("logic_valid_target", 0.60);
    criteria.put("logic_valid_passed", results.getLogicValidRate() >= 0.60);
    criteria.put("novel_target", 0.70);
    criteria.put("novel_passed", results.getNovelRate() >= 0.70);
    criteria.put(
        "overall_go",
        results.getSyntaxValidRate() >= 0.80
            && results.getLogicValidRate() >= 0.60
            && results.getNovelRate() >= 0.70);
    map.put("success_criteria", criteria);

    List<Map<String, Object>> strategyList = new ArrayList<>();
    for (ExperimentRunner.GenerationAttempt a : results.getAttempts()) {
      Map<String, Object> entry = new LinkedHashMap<>();
      entry.put("index", a.getIndex());
      entry.put("name", a.getConfig() != null ? a.getConfig().getName() : null);
      entry.put("syntax_valid", a.getValidationReport().isSyntaxValid());
      entry.put("logic_valid", a.getValidationReport().isLogicValid());
      entry.put("novel", a.getValidationReport().isNovel());
      entry.put("valid", a.getValidationReport().isValid());
      entry.put("errors", a.getValidationReport().getErrors());
      entry.put("generation_time_ms", a.getGenerationTimeMs());
      entry.put("creativity_hint", a.getCreativityHint());
      strategyList.add(entry);
    }
    map.put("attempts", strategyList);

    List<Map<String, Object>> rankings = new ArrayList<>();
    int rank = 1;
    for (ExperimentRunner.RankedStrategy rs : results.getRankedStrategies()) {
      Map<String, Object> entry = new LinkedHashMap<>();
      entry.put("rank", rank++);
      entry.put("name", rs.getBacktestResult().getStrategyName());
      entry.put("gross_return", rs.getBacktestResult().getGrossReturn());
      entry.put("sharpe_approx", rs.getBacktestResult().getSharpeApprox());
      entry.put("win_rate", rs.getBacktestResult().getWinRate());
      entry.put("num_trades", rs.getBacktestResult().getNumTrades());
      entry.put("vs_buy_hold", rs.getBacktestResult().getVsBuyHoldRatio());
      entry.put("error", rs.getBacktestResult().getError());
      rankings.add(entry);
    }
    map.put("rankings", rankings);

    return map;
  }
}
