load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "TimestampsTest",
    srcs = ["TimestampsTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestream/time:timestamps",
        "//third_party:guava",
        "//third_party:junit",
        "//third_party:protobuf_java",
        "//third_party:truth",
    ],
)
