name: Tidy Bazel Modules

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "BUILD"
      - "BUILD.bazel"
      - "WORKSPACE"
      - "WORKSPACE.bazel"
      - "MODULE.bazel"
      - "**/BUILD"
      - "**/BUILD.bazel"
      - "**/WORKSPACE"
      - "**/WORKSPACE.bazel"
      - "**/MODULE.bazel"
      - "**/*.bzl"
      - "**/*.BUILD"

permissions:
  contents: read
  pull-requests: write

jobs:
  tidy-bazel-modules:
    name: runner / bazel-mod-tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          bazelrc: |
            build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Run bazel mod tidy
        run: bazel mod tidy

      - name: Check for changes
        id: verify_changed_files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Print detected diff
        if: steps.verify_changed_files.outputs.changed == 'true'
        run: |
          echo "Detected changes by 'bazel mod tidy':"
          git --no-pager diff

      - name: Suggest tidy changes
        if: steps.verify_changed_files.outputs.changed == 'true'
        run: |
          git diff | reviewdog -f=diff -name="bazel-mod-tidy" -reporter=github-pr-review -level=warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Alternative approach using action-suggester (choose one)
      # - name: Suggest tidy changes (alternative)
      #   if: steps.verify_changed_files.outputs.changed == 'true'
      #   uses: reviewdog/action-suggester@v1
      #   with:
      #     tool_name: bazel-mod-tidy
      #     level: warning
      #     filter_mode: diff_context
      #     fail_level: none
      #     cleanup: false  # Important: don't clean up changes
      #   env:
      #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
