name: "buildifier-formatter"
on:
  pull_request:
    paths:
      - "BUILD"
      - "BUILD.bazel"
      - "WORKSPACE"
      - "WORKSPACE.bazel"
      - "MODULE.bazel"
      - "**/BUILD"
      - "**/BUILD.bazel"
      - "**/WORKSPACE"
      - "**/WORKSPACE.bazel"
      - "**/MODULE.bazel"
      - "**/*.bzl"
      - "**/*.BUILD"
permissions:
  contents: read
  pull-requests: write
jobs:
  format:
    name: runner / buildifier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup buildifier
        uses: jbajic/setup-buildifier@v1
      - name: Format files using buildifier
        run: buildifier --mode=fix -r .
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Annotate diff changes using reviewdog
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: buildifier
