name: 'ktlint-formatter'
on:
  pull_request:
    paths: ['**/*.kt', '**/*.kts']
permissions:
  contents: read
  pull-requests: write
jobs:
  format:
    name: runner / ktlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.5.0/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/
      - name: Auto-fix what ktlint can fix
        run: ktlint -F "**/*.kt" "**/*.kts"
        continue-on-error: true
      - name: Check for auto-fixed changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Suggest auto-fixed changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: ktlint-format
      - name: Report remaining ktlint violations
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          fail_on_error: false
