name: Release Tradestream Artifacts
on:
  push:
    branches:
      - main
      - develop

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine Suffix
        id: suffix
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "suffix=-develop" >> $GITHUB_ENV
          else
            echo "suffix=" >> $GITHUB_ENV
          fi

      - name: Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}${{ env.suffix }}-prerelease${increment}"
          enable_prerelease_mode: true

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push https://$GITHUB_ACTOR:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }} --tags
