name: Release Tradestream Artifacts (Simplified)
on:
  push:
    branches:
      - main
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          namespace: "${{ steps.extract_branch.outputs.branch }}"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}"

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push https://$GITHUB_ACTOR:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }} --tags

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          bazelrc: |
            build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}

      # Build and push all images with the new tag
      - name: Push the Candle Ingestor image
        run: |
          bazel run //services/candle_ingestor:push_candle_ingestor_image \
            -- \
            --tag ${{ steps.version.outputs.version_tag }}
      
      - name: Push the Top Crypto Updater image
        run: |
          bazel run //services/top_crypto_updater:push_top_crypto_updater_image \
            -- \
            --tag ${{ steps.version.outputs.version_tag }}
      
      - name: Push the Strategy Discovery Request Factory image
        run: |
          bazel run //services/strategy_discovery_request_factory:push_strategy_discovery_request_factory_image \
            -- \
            --tag ${{ steps.version.outputs.version_tag }}
      
      - name: Push the Strategy Discovery Pipeline image
        run: |
          bazel run //src/main/java/com/verlumen/tradestream/discovery:push_image \
            -- \
            --tag ${{ steps.version.outputs.version_tag }}
      
      - name: Push the Strategy Consumer image
        run: |
          bazel run //services/strategy_consumer:push_strategy_consumer_image \
            -- \
            --tag ${{ steps.version.outputs.version_tag }}
      
      - name: Push the Strategy Monitor API image
        run: |
          bazel run //services/strategy_monitor_api:push_strategy_monitor_api_image \
            -- \
            --tag ${{ steps.version.outputs.version_tag }}
      
      - name: Push the Strategy Monitor UI image
        run: |
          bazel run //ui/strategy-monitor:push_strategy_monitor_ui_image \
            -- \
            --tag ${{ steps.version.outputs.version_tag }}

      # Update MODULE.bazel version (keeping this as it's still needed)
      - name: Update MODULE.bazel version
        run: |
          echo "Updating MODULE.bazel to version ${{ steps.version.outputs.version_tag }}"
          sed -i.bak '/^module(/,/^)/ s/\(version\s*=\s*"\)[^"]\+"/\1'"${{ steps.version.outputs.version_tag }}"'"/' MODULE.bazel
        shell: bash

      # Commit and push MODULE.bazel changes only
      - name: Commit and Push MODULE.bazel Changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git add MODULE.bazel
          git commit -m "Bump version to ${{ steps.version.outputs.version_tag }}" || echo "No changes to commit"
          git push https://$GITHUB_ACTOR:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
