name: Release Tradestream Artifacts

on:
  push:
    branches:
      - main
      - develop

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      DATA_INGESTION_REPO: tradestreamhq/tradestream-data-ingestion
      DATA_INGESTION_SECTION_KEY: dataIngestion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          enable_prerelease_mode: true

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push https://$GITHUB_ACTOR:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }} --tags

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Create image tag
        shell: bash
        run: echo "image_tag=${{ steps.version.outputs.version_tag }}-${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_OUTPUT
        id: create_image_tag

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the Data Ingestion image
        run: |
          bazel run //src/main/java/com/verlumen/tradestream/ingestion:push_image \
            --verbose_failures \
            --sandbox_debug \
            -- \
            --tag ${{ steps.create_image_tag.outputs.image_tag }}

      - name: Inspect Docker Manifest
        run: |
          docker manifest inspect tradestreamhq/tradestream-data-ingestion:${{ steps.create_image_tag.outputs.image_tag }}
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Install yq
        run: |
          sudo wget -O /usr/bin/yq https://github.com/mikefarah/yq/releases/download/v4.35.1/yq_linux_amd64
          sudo chmod +x /usr/bin/yq

      - name: Update values.yaml with new image tag
        run: |
          yq eval-all '
            . as $item ireduce ({}; . * $item ) |
            .["${{ env.DATA_INGESTION_SECTION_KEY }}"].image.repository = "${{ env.DATA_INGESTION_REPO }}" |
            .["${{ env.DATA_INGESTION_SECTION_KEY }}"].image.tag = "${{ steps.create_image_tag.outputs.image_tag }}"
          ' charts/tradestream/values.yaml > charts/tradestream/values.yaml.tmp
          mv charts/tradestream/values.yaml.tmp charts/tradestream/values.yaml

      - name: Commit updated values.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git add charts/tradestream/values.yaml
          git commit -m "Update values.yaml: Set ${{ env.DATA_INGESTION_SECTION_KEY }} image to ${{ steps.create_image_tag.outputs.image_tag }}" || echo "No changes to commit"
          git push https://$GITHUB_ACTOR:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
