load("@rules_java//java:defs.bzl", "java_library")

java_library(
  name = "candle_author",
  srcs = ["CandleAuthor.java"],
  deps = [
    "//third_party:beam_sdks_java_core",
    "//third_party:joda_time",
    "//third_party:protobuf_java_util",
  ],
)
